### ISSUE TITLE
Enter-to-search fails on Firefox (nightly build)

### ISSUE THREAD

**Issue by alexander-bauer** [alexander-bauer/distru#17]
Brought to attention by @danry25.

**Comment by danry25** [comment]
Looks like there are still a few issues with the background gradients not filling right & the search box loping off the top & bottom pixels of a search, see this screen shot I took: http://imgur.com/Ehfnc

**Comment by lukevers** [comment]
Thanks, @danry25, I'll take a look at that. I know the background wasn't working so I added a fallback colour so it wasn't just white. I didn't know about the line-height problem. Thanks.

**Comment by danry25** [comment]
Looks like the gradient now properly displays in Firefox & the line height issue is resolved. Thanks for taking a look at it!

**Comment by lukevers** [comment]
Closed by 829489ccc264d0fe0c397b757b548fa9e2b95e1a
