### ISSUE TITLE
Sometimes something can be added and the title says "No Title"

### ISSUE THREAD

**Issue by lukevers** [alexander-bauer/distru#33]

**Comment by alexander-bauer** [comment]
The "No Title" is intentional for things which don't have `<title>` tags. Perhaps this should be replaced by the description field?

**Comment by lukevers** [comment]
I think the "No Title" thing is a great idea for things that don't have the `<title>` tag, but I feel like there should be a way to make some sort of a title. Maybe if it doesn't have a title, use `[website name] : [tag]` or something similar.
