### ISSUE TITLE
CSS and related files make Distru non-relocatable

### ISSUE THREAD

**Issue by alexander-bauer** [alexander-bauer/distru#59]
Distru tries to load `ui/search.css`, and some other files in `ui/` when serving the web interface. I'm not quite sure how this should be fixed; they _could_ be kept in a resources directory, such as `/etc/distru/`, but that's slightly inelegant, as is the alternative of incorporating them in the source.

**Comment by lukevers** [comment]
Thinking about it another way, this also does allow people to style Distru however they want.

**Comment by alexander-bauer** [comment]
Yeah, but the install process for anyone not intimately familiar with it is sort of a bitch.

We probably _should_ keep them separate, but not like they are now. They should probably be moved to something like `/etc/distru/` in an install script.

**Comment by lukevers** [comment]
Yeah, I know. Is there a way to include it in a binary?

**Comment by alexander-bauer** [comment]
I don't know of an elegant way to do it, really. The easiest is probably to include an install script in the repository which moves (or symlinks) the style and html files to a data repository, along with compiling Distru, ensuring that the configuration file is writable, and starting Distru as a daemon.
