### ISSUE TITLE
Should probably use UDP

### ISSUE THREAD

**Issue by alexander-bauer** [alexander-bauer/distru#6]
UDP is better designed for Distru's purposes. The problem with this is that some of the server/client code needs to be slightly restructured to use `UDPConn` objects instead of `Conn`s established on TCP.

**Comment by alexander-bauer** [comment]
If this is going to happen, it needs to happen before `1.0`.

**Comment by lukevers** [comment]
Why not [both](http://ps3.mmgn.com/Lib/Images/Articles/Normal/5-Reasons-Why-PS-All-Stars-Is-Not-A-Smash-Bros-Clone-1090557.jpg)?

**Comment by alexander-bauer** [comment]
@lukevers ಠ_ಠ

**Comment by alexander-bauer** [comment]
For the time being, at least, this is not a problem. In the future, this may be reopened.
