### ISSUE TITLE
Sometimes mesh.lukevers.com, when indexing, doesn't index itself.

### ISSUE THREAD

**Issue by lukevers** [alexander-bauer/distru#69]
mesh.lukevers.com:9048/search/distru

Sometimes it displays a result from itself, which it should because it indexes itself, and sometimes it doesn't. This is new. Ever since @SashaCrofter _fixed_ something.

**Comment by alexander-bauer** [comment]
> _fixed_

@lukevers ಠ_ಠ

**Comment by lukevers** [comment]
Confirmed to be introduced since `v0.10.1` 09964cb5ebd834a0e521ab7265ce1cbbfb667b1c

**Comment by lukevers** [comment]
Not sure if it's still doing this. It doesn't seem like it. Maybe somewhere between `v0.10.1` and `v0.10.10` it was fixed? I'm going to close this because it seems fixed, but I'll open it if I feel like it's happening again.
