### ISSUE TITLE
[calc] evaluations

### ISSUE THREAD

**Issue by alexander-bauer** [alexander-bauer/distru#74]
When a calculation is performed, but it is also paired with a boolean evaluation, Distru should indicate whether the evaluation is true or false. For example, `2 * 10 == 20` would result in `true`. Similarly, `2 * 10 == 4 * 5` should also evaluate properly. `>`, `<`, `>=`, and `<=` should also be implemented.

**Comment by lukevers** [comment]
I also want to add more basic functions, like !, square root, ^, et cetera. If anyone has more ideas, write them here.

**Comment by lukevers** [comment]
I'm just using random numbers as an example for each of these.

Absolute Value: `abs -18` ... `18`
Factorial: `5!` ... `120`
Square Root: `sqrt 4` ... `2`
Power: `4^3` ... `64`
